# Imports
include ../../.cache/wal/colors-kitty.conf

# Style
font_family 0xProto Nerd Font
cursor_trail 6
window_padding_width 5

# General
confirm_os_window_close 0
# Dinamically update colorscheme with pywal16
allow_remote_control yes
listen_on unix:@mykitty
