# Default hyprpaper configuration for colorshell
# Added by the install.sh script, because there was no wallpaper set before

splash = true
wallpaper {
    monitor = *
    path = /usr/share/hypr/wall2.png
    fit_mode = cover
}
