import { register } from "ags/gobject";
import Gio from "gi://Gio?version=2.0";
import GObject from "gi://GObject?version=2.0";
import { createSubscription, encoder, getPID, isInstalled, killProc } from "./utils";
import { Shell } from "../app";
import { generalConfig } from "../config";
import { Notifications } from "./notifications";


/** wrapper module for hypridle */
@register({ GTypeName: "ClshIdleDaemon" })
export class Idle extends GObject.Object {
    private static instance: Idle;

    #daemon: Gio.Subprocess|null = null;
    #file: Gio.File = Gio.File.new_for_path(`${Shell.runtimeConfigDir.peek_path()}/hypridle.conf`);
    #generalKeys: Array<keyof Idle.GeneralConfig> = [
        "lock_cmd",
        "unlock_cmd",
        "on_lock_cmd",
        "on_unlock_cmd",
        "before_sleep_cmd",
        "after_sleep_cmd",
        "ignore_dbus_inhibit",
        "ignore_systemd_inhibit",
        "ignore_wayland_inhibit",
        "inhibit_sleep"
    ];

    
    constructor() {
        super();

        if(!isInstalled("hypridle")) {
            console.log("Idle: `hypridle` program not found, idle daemon features are disabled");
            return;
        }

        const pid = getPID("hypridle");
        if(pid !== undefined)
            killProc(pid);

        this.write().catch(console.error).then(() => {
            this.restartDaemon();
        });


        // hot-reload
        createSubscription(
            generalConfig.bindProperty("idle"),
            () => this.write().catch(console.error).then(() => this.restartDaemon())
        );
    }

    /** kills the idle daemon */
    quit(): void {
        try {
            this.#daemon?.force_exit();
        } catch(e) {
            throw new Error(`Idle: Failed to quit daemon: ${(e as Error).message}`);
        }
    }

    /** starts/restarts the idle daemon */
    restartDaemon(): void {
        if(this.#daemon !== null)
            this.quit();

        this.#daemon = Gio.Subprocess.new(
            ["hypridle", "--config", this.#file.peek_path()!],
            Gio.SubprocessFlags.STDOUT_SILENCE | Gio.SubprocessFlags.STDERR_PIPE
        );
    }

    /** generates a hypridle config file from colorshell idle config.
      * @returns a valid hypridle config file's content */
    private generateConfig(): string {
        const listeners = generalConfig.getProperty("idle.listeners") ?? {} as Record<string, Idle.Listener>;
        const lockTimeout = generalConfig.getProperty("idle.lock_timeout", "number");


        return `\
# This file was automatically generated by colorshell

general {
${this.#generalKeys.map((key, i, arr) => {
    const value = generalConfig.getProperty(`idle.${key}`);

    return value !== undefined && value !== null ?
        `${" ".repeat(4)}${key} = ${value}${i < arr.length - 1 ? "\n" : ""}`
    : "";
}).join("")}
}

listener {
    timeout = ${lockTimeout}
    on-timeout = colorshell lock
}

${Object.keys(listeners).map(name => {
    const listener = listeners[name as keyof typeof listeners] as Idle.Listener;

    if(Object.keys(listener).length < 1) 
        return "";

    if(listener.timeout == null || typeof listener.timeout !== "number") {
        Notifications.getDefault().sendNotification({
            appName: "colorshell",
            summary: "Config error",
            body: `No timeout set for listener ${name}. Please set a valid "timeout" value(seconds) for it to work`,
        });

        return "";
    }

    const onResume = listener["on_resume"] ?? (listener as any)["on-resume"];
    const onTimeout = listener["on_timeout"] ?? (listener as any)["on-timeout"];

    if(typeof onResume !== "string" && typeof onTimeout !== "string") {
        Notifications.getDefault().sendNotification({
            appName: "colorshell",
            summary: "Config error",
            body: `You must set one of the "on_*" properties to create a listener for "${name}".`
        });
        return "";
    }

    return `\
listener {
    timeout = ${listener.timeout}
    ${typeof onResume === "string" ? `on-resume = ${onResume}` : ""}
    ${typeof onTimeout === "string" ? `on-timeout = ${onTimeout}` : ""}
}`;
}).join('\n')}`;

    }

    private async write(): Promise<void> {
        const content = this.generateConfig();

        if(!content.trim())
            return;

        return new Promise((resolve, reject) => {
            this.#file.replace_contents_bytes_async(
                encoder.encode(content), null, false, Gio.FileCreateFlags.REPLACE_DESTINATION, null, (_, res) => {
                    const [ok] = this.#file.replace_contents_finish(res);

                    if(!ok) {
                        reject(new Error("Idle: Failed to write hypridle config! Do we have permissions?"));
                        return;
                    }

                    resolve();
                }
            );
        });
    }

    public static getDefault(): Idle {
        if(!this.instance)
            this.instance = new Idle();

        return this.instance;
    }
}

export namespace Idle {
    export type Listener = {
        timeout: number;
        on_timeout?: string;
        on_resume?: string;
        ignore_inhibit?: boolean;
    };

    export type GeneralConfig = {
        lock_cmd?: string;
        unlock_cmd?: string;
        on_lock_cmd?: string;
        on_unlock_cmd?: string;
        before_sleep_cmd?: string;
        after_sleep_cmd?: string;

        ignore_dbus_inhibit: boolean;
        ignore_systemd_inhibit: boolean;
        ignore_wayland_inhibit: boolean;
        inhibit_sleep: InhibitSleep;
    }

    export type Config = {
        /** this is a colorshell-specific property. it's used
          * for the default screen lock listener's timeout */
        lock_timeout: 3600;
        listeners: Record<string, Idle.Listener>;
    } & Partial<GeneralConfig>;

    export type InhibitSleep = 0|1|2|3;
}
