
###############
## AUTOSTART ##
###############

# Wiki: https://wiki.hyprland.org/Configuring/Keywords/#executing


# Services/Daemons
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl enable --user --now hypridle
exec-once = systemctl enable --user --now gnome-keyring-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Tools
exec-once = systemctl enable --user --now hyprpaper

# Scripts
exec-once = sh $HOME/.config/hypr/scripts/gen-pywal.sh
exec-once = sh $HOME/.config/hypr/scripts/night-light-check.sh

# Other
exec-once = ags run --log-file $HOME/ags.log

# Apps
exec-once = vesktop --start-minimized
exec-once = steam -silent
