
###############
## AUTOSTART ##
###############

exec-once = systemctl enable --user --now hyprpolkitagent.service # Hyprland Policy Kit
exec-once = hyprpaper # Wallpaper
exec-once = mako # Notification Daemon
exec-once = eww daemon --no-daemonize # Eww service
exec-once = sh $HOME/.config/eww/scripts/eww-window.sh open bar
exec-once = hypridle # Idle daemon

# Load pywal from cache || generate pywal colorscheme
exec-once = sh -c "[[ -d $HOME/.cache/wal ]] && wal -R || wal -q -t --cols16 darken -i $(cat '$HOME/.config/hypr/hyprpaper.conf' | grep '$wallpaper =' | sed -e 's/^$wallpaper = //')"

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store # Stores text
exec-once = wl-paste --type image --watch cliphist store # Stores images

# Apps 
exec-once = /bin/vesktop --start-minimized
exec-once = /bin/steam-runtime -silent
