
###############################
## Retrozinn's Hyprland Dots ##
###############################

# From https://github.com/retrozinndev/Hyprland-Dots
# Made with lots of love 󰋑 , by retrozinndev 
# Licensed under the MIT License


# Shell configurations (it's not recommended to modify)
source = ./shell/hyprland.conf

# User configurations (please use the `user/` config directory
source = ./user/hyprland.conf
