
############################
##  WINDOW & LAYER RULES  ##
############################

# See https://wiki.hyprland.org/Configuring/Window-Rules for
# more information on how to do this

# Floating windows
windowrule = float, class:moe.launcher.*
windowrule = float, class:com.github.rafostar.Clapper
windowrule = float, class:xdg-desktop-portal.*
windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = float, class:blueberry.py
windowrule = float, class:org.gnome.Loupe
windowrule = float, class:mcpelauncher-webview
windowrule = float, class:org.gnome.Calculator
windowrule = float, class:io.mrarm.mcpelauncher-ui-qt
windowrule = float, class:Resources
windowrule = float, class:io.github.kaii_lb.Overskride
windowrule = float, class:nm-connection-editor

# Resize
windowrule = size 50% 50%, class:org.pulseaudio.pavucontrol
windowrule = size 50% 50%, class:blueberry.py
windowrule = size 50% 50%, class:io.github.kaii_lb.Overskride
windowrule = size 70% 70%, class:io.mrarm.mcpelauncher-ui-qt

# Moving
windowrule = move 49.27% 7.28%, class:org.pulseaudio.pavucontrol
windowrule = move 49.27% 7.28%, class:blueberry.py
windowrule = move 49.27% 7.28%, class:io.github.kaii_lb.Overskride
windowrule = movetoworkspace e, class:org.pulseaudio.pavucontrol

# Animations
windowrule = animation slide right, class:org.pulseaudio.pavucontrol
windowrule = animation slide right, class:blueberry.py
windowrule = animation slide right, class:io.github.kaii_lb.Overskride
windowrule = animation gnomed, class:moe.launcher..*
windowrule = animation gnomed, class:hyprpolkitagent
layerrule = animation slide, swaync-control-center
layerrule = animation fade, selection
layerrule = animation fade, waybar
layerrule = animation fade, hyprpaper
layerrule = animation slide right, swaync-notification-window
layerrule = animation fade, hyprpicker
layerrule = animation fade, anyrun
layerrule = animation fade, ^(eww-(.*))$
layerrule = animation slide, eww-cc
layerrule = animation fade, control-center
layerrule = animation fade, center-window # Bruh i need a better name for this :skull:
layerrule = animation fade, logout-menu
layerrule = animation fade, wallpaper
layerrule = animation slide bottom, apps-window
layerrule = animation fade, runner
layerrule = animation fade, ask-popup
layerrule = animation fade, entry-popup
layerrule = animation fade, background-window

# Opacity
windowrule = opacity .95 .95, class:kitty
windowrule = opacity .88 .88, class:spotify
windowrule = opacity .88 .88, class:hyprpolkitagent

# No blur
windowrule = noblur, class:^()$, title:^()$ # Removes blur from context menus
windowrule = noblur, class:steam(.*)$

# Layer Blur list
layerrule = blur, waybar
layerrule = blur, eww-bar
layerrule = blur, eww-calendar
layerrule = blur, eww-cc
layerrule = blur, eww-volume
layerrule = blur, eww-powermenu
layerrule = blur, top-bar
layerrule = blur, osd
layerrule = blur, control-center
layerrule = blur, center-window
layerrule = blur, logout-menu
layerrule = blur, runner
layerrule = blur, ask-popup
layerrule = blur, entry-popup
layerrule = blur, floating-notifications
layerrule = blur, apps-window
layerrule = ignorealpha .7, runner
layerrule = ignorealpha .6, eww-volume
layerrule = ignorealpha .55, eww-bar
layerrule = ignorealpha .5, eww-calendar
layerrule = ignorealpha .7, eww-cc
layerrule = ignorealpha .4, osd
layerrule = ignorealpha .55, top-bar
layerrule = ignorealpha .6, ask-popup
layerrule = ignorealpha .6, entry-popup
layerrule = ignorealpha .7, control-center
layerrule = ignorealpha .5, apps-window
layerrule = ignorealpha .7, center-window
layerrule = ignorealpha .7, floating-notifications

# Others
windowrule = noinitialfocus, class:Anydesk, title:anydesk

# Suppress maximize event from windows
windowrule = suppressevent maximize, class:.*
