
# colorshell configuration, please don't modify unless you know what you're doing!

# Daemons
exec-once = $exec ibus start # use ibus as input method (fixes character compose not working in gtk apps)
exec-once = $exec wl-paste --type text --watch cliphist store
exec-once = $exec wl-paste --type image --watch cliphist store

# Tools
exec-once = systemctl start --user --now hyprsunset
exec-once = systemctl start --user --now hyprpaper
