# colorshell-specific configuration, please don't modify unless you know what you're doing!

bind = SUPER, SPACE, exec, colorshell runner

bind = , Print, exec, colorshell screenshot
bind = SUPER, Print, exec, colorshell screenshot full

# Restart colorshell
bind = SUPER, F7, exec, timeout 0.6s colorshell quit && $exec colorshell.desktop || kill $(cat $XDG_RUNTIME_DIR/colorshell/.pid) ; $exec colorshell

bind = SUPER, N, exec, colorshell toggle control-center
bind = SUPER, M, exec, colorshell toggle center-window
bind = SUPER, L, exec, colorshell lock
bind = SUPER, V, exec, colorshell runner '>'
bind = SUPER, W, exec, colorshell runner '\##'

bind = SUPER, SUPER_l, exec, colorshell peek-workspace-num

binde = , XF86AudioLowerVolume, exec, colorshell volume sink-decrease 5 # Decrease volume
binde = , XF86AudioRaiseVolume, exec, colorshell volume sink-increase 5 # Increase volume
bind = , XF86AudioMute, exec, colorshell volume sink-mute # Mute
bind = , XF86AudioPrev, exec, colorshell media previous # Previous media
bind = , XF86AudioNext, exec, colorshell media next # Next media
bind = , XF86AudioPlay, exec, colorshell media play-pause # Toggle Play/Pause media

bind = , XF86MonBrightnessDown, exec, brightnessctl -c backlight s 5%- # Lower monitor brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl -c backlight s +5% # Increase monitor brightness
