# colorshell-specific configuration, please don't modify unless you know what you're doing!

unbind = SUPER, SPACE
bind = SUPER, SPACE, exec, colorshell runner

unbind = , Print
bind = , Print, exec, colorshell screenshot
unbind = ALT, Print
bind = ALT, Print, exec, colorshell screenshot active
unbind = SUPER, Print
bind = SUPER, Print, exec, colorshell screenshot full

# Restart colorshell
unbind = SUPER, F7
bind = SUPER, F7, exec, colorshell reload

unbind = SUPER, N
bind = SUPER, N, exec, colorshell toggle control-center
unbind = SUPER, M
bind = SUPER, M, exec, colorshell toggle center-window
unbind = SUPER, L
bind = SUPER, L, exec, colorshell lock
unbind = SUPER, V
bind = SUPER, V, exec, colorshell runner '>'
unbind = SUPER, W
bind = SUPER, W, exec, colorshell runner '\##'

bind = SUPER, SUPER_l, exec, colorshell peek-workspace-num

unbind = , XF86AudioLowerVolume
binde = , XF86AudioLowerVolume, exec, colorshell volume sink-decrease 5 # Decrease volume
unbind = , XF86AudioRaiseVolume
binde = , XF86AudioRaiseVolume, exec, colorshell volume sink-increase 5 # Increase volume
unbind = , XF86AudioMute
bind = , XF86AudioMute, exec, colorshell volume sink-mute # Mute
unbind = , XF86AudioPrev
bind = , XF86AudioPrev, exec, colorshell media previous # Previous media
unbind = , XF86AudioNext
bind = , XF86AudioNext, exec, colorshell media next # Next media
unbind = , XF86AudioPlay
bind = , XF86AudioPlay, exec, colorshell media play-pause # Toggle Play/Pause media

unbind = , XF86MonBrightnessDown
bind = , XF86MonBrightnessDown, exec, brightnessctl -c backlight s 5%- # Lower monitor brightness
unbind = , XF86MonBrightnessUp
bind = , XF86MonBrightnessUp, exec, brightnessctl -c backlight s +5% # Increase monitor brightness
