# colorshell configuration, please don't modify unless you know what you're doing!

# XDG Vars
env = XDG_CONFIG_HOME, $HOME/.config
env = XDG_CACHE_HOME, $HOME/.cache
env = XDG_DATA_HOME, $HOME/.local/share
env = XDG_STATE_HOME, $HOME/.local/state
