# colorshell configuration, please don't modify unless you know what you're doing!

source = ./vars.conf
source = ./environment.conf
source = ./bindings.conf
source = ./decorations.conf
source = ./autostart.conf
source = ./rules.conf
